name: AWS Lambda Zip Deploy - Python
author: Ope Usman
description: Zip deploy to AWS Lambda with requirements in a separate layer.
inputs:
  lambda_layer_arn:
    description: The ARN for the Lambda layer the dependencies should be pushed to without the version (every push is a new version).
    required: true
  lambda_function_name:
    description: The Lambda function name. Check the AWS docs/readme for examples.
    required: true
runs: 
  using: composite
  steps:
    - id: Push-to-AWS
      run: |
        pwd
        ./deploy.sh
      shell: sh
branding:
  icon: 'cloud-lightning'
  color: 'white'